CLASS zcl_pdf_renderer DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.

    INTERFACES zif_renderer .
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_PDF_RENDERER IMPLEMENTATION.


  METHOD zif_renderer~render.
   result = |'Rendering PDF:', { iv_content }|.
  ENDMETHOD.
ENDCLASS.
